## AUTO-GENERATED by ``brief_index_build.nim`` — do not edit by hand.
##
## Rerun ``just editor-build`` (which invokes the build script) to
## refresh this file from the live ``briefs/`` directory.

import std/[json, tables, options, strutils]
import isonim/editor/design_review/brief_format
import isonim/editor/design_review/brief_index
import isonim/editor/types

const BUILT_IN_BRIEF_INDEX_JSON*: string = """{
  "briefs": [],
  "byPreview": {},
  "errors": []
}"""
proc storyKindFromName(s: string): StoryKind =
  case s
  of "skFoundation": skFoundation
  of "skComponent": skComponent
  of "skPattern": skPattern
  of "skPage": skPage
  of "skFlow": skFlow
  of "skGuideline": skGuideline
  of "skVectorSymbol": skVectorSymbol
  else: skPage

proc previewBackendFromName(s: string): PreviewBackend =
  case s
  of "web": pbWeb
  of "tui": pbTui
  of "gpui": pbGpui
  of "freya": pbFreya
  of "cocoa": pbCocoa
  of "android": pbAndroid
  of "ios": pbIos
  else: pbWeb

proc briefKindFromName(s: string): BriefKind =
  case s
  of "render": bkRender
  of "interaction": bkInteraction
  of "accessibility": bkAccessibility
  of "copy": bkCopy
  of "chrome": bkChrome
  of "component": bkComponent
  of "foundation": bkFoundation
  of "pattern": bkPattern
  of "vectorsymbol": bkVectorSymbol
  of "guideline": bkGuideline
  else: bkRender

proc storyRefFromJson(node: JsonNode): StoryRef =
  result.group = node["group"].getStr()
  result.name = node["name"].getStr()
  result.kind = storyKindFromName(node["kind"].getStr())
  result.index = node["index"].getInt()

proc coverageFromJson(node: JsonNode): BriefPreviewCoverage =
  result.storyRef = storyRefFromJson(node["storyRef"])
  result.backends = @[]
  for b in node["backends"].items:
    result.backends.add previewBackendFromName(b.getStr())

proc viewportFromJson(node: JsonNode): BriefViewport =
  result.width = node["width"].getInt()
  result.height = node["height"].getInt()
  result.label = node["label"].getStr()

proc dimensionFromJson(node: JsonNode): BriefScoringDimension =
  result.id = node["id"].getStr()
  result.label = node["label"].getStr()
  result.weight = node["weight"].getFloat()
  result.scaleMin = node["scaleMin"].getInt()
  result.scaleMax = node["scaleMax"].getInt()

proc briefFromJson(node: JsonNode): Brief =
  result.briefId = node["briefId"].getStr()
  result.schemaVersion = node["schemaVersion"].getInt()
  result.kind = briefKindFromName(node["kind"].getStr())
  result.title = node["title"].getStr()
  result.sourceFile = node["sourceFile"].getStr()
  result.bodyMarkdown = node["bodyMarkdown"].getStr()
  result.reviewerSchemaVersion = node["reviewerSchemaVersion"].getInt()
  result.relatedBriefs = @[]
  for r in node["relatedBriefs"].items:
    result.relatedBriefs.add r.getStr()
  result.coversPreviews = @[]
  for c in node["coversPreviews"].items:
    result.coversPreviews.add coverageFromJson(c)
  result.captureViewports = @[]
  for v in node["captureViewports"].items:
    result.captureViewports.add viewportFromJson(v)
  result.scoringDimensions = @[]
  for d in node["scoringDimensions"].items:
    result.scoringDimensions.add dimensionFromJson(d)
  result.extra = initTable[string, string]()
  if "extra" in node:
    for k, v in node["extra"].pairs:
      result.extra[k] = v.getStr()

proc builtInBriefIndex*(): BriefIndex =
  ## Reconstruct the ``BriefIndex`` baked at build time. Returned by
  ## value so consumers can treat it as an immutable snapshot.
  result = BriefIndex(
    byBriefId: initOrderedTable[string, Brief](),
    byPreview: initOrderedTable[string, seq[string]](),
    errors: @[]
  )
  if BUILT_IN_BRIEF_INDEX_JSON.strip().len == 0:
    return
  let doc = parseJson(BUILT_IN_BRIEF_INDEX_JSON)
  for entry in doc["briefs"].items:
    let b = briefFromJson(entry)
    result.byBriefId[b.briefId] = b
  for previewId, briefIds in doc["byPreview"].pairs:
    var ids: seq[string] = @[]
    for id in briefIds.items:
      ids.add id.getStr()
    result.byPreview[previewId] = ids
  for e in doc["errors"].items:
    result.errors.add BriefIndexError(
      path: e["path"].getStr(),
      message: e["message"].getStr()
    )
