## REV-M2: Build-time helper that bakes a ``BriefIndex`` into the
## editor's JS bundle.
##
## Invoked from the Justfile's ``editor-build`` recipe before
## ``nim js`` compiles the bundle:
##
##   nim r src/isonim/editor/design_review/brief_index_build.nim \
##         --briefs path/to/briefs \
##         --out src/isonim/editor/design_review/brief_index_static.nim
##
## The default ``--briefs`` path is ``isonim-examples/briefs`` if
## present (relative to the repo root), otherwise an empty path that
## produces an empty index. The generator never raises on parse errors;
## it records them in the baked-in index just like
## ``buildBriefIndex`` does at run-time.

import std/[os, parseopt, strutils, json, tables]
import isonim/editor/design_review/brief_format
import isonim/editor/design_review/brief_index
import isonim/editor/types

# --------------------------------------------------------------------------- #
#  JSON serialisation helpers.
# --------------------------------------------------------------------------- #

proc storyKindToJson(k: StoryKind): JsonNode = %($k)

proc storyRefToJson(s: StoryRef): JsonNode =
  %*{
    "group": s.group,
    "name":  s.name,
    "kind":  storyKindToJson(s.kind),
    "index": s.index
  }

proc backendsToJson(bs: seq[PreviewBackend]): JsonNode =
  result = newJArray()
  for b in bs:
    result.add %previewBackendToString(b)

proc coverageToJson(c: BriefPreviewCoverage): JsonNode =
  %*{
    "storyRef": storyRefToJson(c.storyRef),
    "backends": backendsToJson(c.backends)
  }

proc viewportToJson(v: BriefViewport): JsonNode =
  %*{
    "width":  v.width,
    "height": v.height,
    "label":  v.label
  }

proc dimensionToJson(d: BriefScoringDimension): JsonNode =
  %*{
    "id":       d.id,
    "label":    d.label,
    "weight":   d.weight,
    "scaleMin": d.scaleMin,
    "scaleMax": d.scaleMax
  }

proc kindToJson(k: BriefKind): string =
  case k
  of bkRender:        "render"
  of bkInteraction:   "interaction"
  of bkAccessibility: "accessibility"
  of bkCopy:          "copy"
  of bkChrome:        "chrome"
  of bkComponent:     "component"
  of bkFoundation:    "foundation"
  of bkPattern:       "pattern"
  of bkVectorSymbol:  "vectorsymbol"
  of bkGuideline:     "guideline"

proc briefToJson(b: Brief): JsonNode =
  result = newJObject()
  result["briefId"] = %b.briefId
  result["schemaVersion"] = %b.schemaVersion
  result["kind"] = %kindToJson(b.kind)
  result["title"] = %b.title
  result["sourceFile"] = %b.sourceFile
  result["bodyMarkdown"] = %b.bodyMarkdown
  result["reviewerSchemaVersion"] = %b.reviewerSchemaVersion
  result["relatedBriefs"] = %b.relatedBriefs
  var coverages = newJArray()
  for c in b.coversPreviews:
    coverages.add coverageToJson(c)
  result["coversPreviews"] = coverages
  var viewports = newJArray()
  for v in b.captureViewports:
    viewports.add viewportToJson(v)
  result["captureViewports"] = viewports
  var dims = newJArray()
  for d in b.scoringDimensions:
    dims.add dimensionToJson(d)
  result["scoringDimensions"] = dims
  var extra = newJObject()
  for k, v in b.extra.pairs:
    extra[k] = %v
  result["extra"] = extra

proc indexToJson(idx: BriefIndex): JsonNode =
  ## Serialise a ``BriefIndex`` to a JSON document. The on-disk shape:
  ##
  ##   { "briefs": [ Brief, ... ],
  ##     "byPreview": { previewId: [briefId, ...] },
  ##     "errors":  [ { path, message }, ... ] }
  result = newJObject()
  var briefs = newJArray()
  for id, b in idx.byBriefId.pairs:
    briefs.add briefToJson(b)
  result["briefs"] = briefs
  var byPreview = newJObject()
  for previewId, briefIds in idx.byPreview.pairs:
    byPreview[previewId] = %briefIds
  result["byPreview"] = byPreview
  var errors = newJArray()
  for e in idx.errors:
    errors.add %*{"path": e.path, "message": e.message}
  result["errors"] = errors

# --------------------------------------------------------------------------- #
#  Driver
# --------------------------------------------------------------------------- #

proc emitStaticModule(json: string; outPath: string) =
  ## Write the generated Nim module.  The ``"""...."""`` triple-quoted
  ## block embeds the JSON verbatim; we escape any closing ``"""`` runs
  ## defensively so the generated file is always syntactically valid.
  let safe = json.replace("\"\"\"", "\"\"&\"\"")  # never appears in practice
  let body = """## AUTO-GENERATED by ``brief_index_build.nim`` — do not edit by hand.
##
## Rerun ``just editor-build`` (which invokes the build script) to
## refresh this file from the live ``briefs/`` directory.

import std/[json, tables, options, strutils]
import isonim/editor/design_review/brief_format
import isonim/editor/design_review/brief_index
import isonim/editor/types

const BUILT_IN_BRIEF_INDEX_JSON*: string = """ & "\"\"\"" & safe & "\"\"\"" & """

proc storyKindFromName(s: string): StoryKind =
  case s
  of "skFoundation": skFoundation
  of "skComponent": skComponent
  of "skPattern": skPattern
  of "skPage": skPage
  of "skFlow": skFlow
  of "skGuideline": skGuideline
  of "skVectorSymbol": skVectorSymbol
  else: skPage

proc previewBackendFromName(s: string): PreviewBackend =
  case s
  of "web": pbWeb
  of "tui": pbTui
  of "gpui": pbGpui
  of "freya": pbFreya
  of "cocoa": pbCocoa
  of "android": pbAndroid
  of "ios": pbIos
  else: pbWeb

proc briefKindFromName(s: string): BriefKind =
  case s
  of "render": bkRender
  of "interaction": bkInteraction
  of "accessibility": bkAccessibility
  of "copy": bkCopy
  of "chrome": bkChrome
  of "component": bkComponent
  of "foundation": bkFoundation
  of "pattern": bkPattern
  of "vectorsymbol": bkVectorSymbol
  of "guideline": bkGuideline
  else: bkRender

proc storyRefFromJson(node: JsonNode): StoryRef =
  result.group = node["group"].getStr()
  result.name = node["name"].getStr()
  result.kind = storyKindFromName(node["kind"].getStr())
  result.index = node["index"].getInt()

proc coverageFromJson(node: JsonNode): BriefPreviewCoverage =
  result.storyRef = storyRefFromJson(node["storyRef"])
  result.backends = @[]
  for b in node["backends"].items:
    result.backends.add previewBackendFromName(b.getStr())

proc viewportFromJson(node: JsonNode): BriefViewport =
  result.width = node["width"].getInt()
  result.height = node["height"].getInt()
  result.label = node["label"].getStr()

proc dimensionFromJson(node: JsonNode): BriefScoringDimension =
  result.id = node["id"].getStr()
  result.label = node["label"].getStr()
  result.weight = node["weight"].getFloat()
  result.scaleMin = node["scaleMin"].getInt()
  result.scaleMax = node["scaleMax"].getInt()

proc briefFromJson(node: JsonNode): Brief =
  result.briefId = node["briefId"].getStr()
  result.schemaVersion = node["schemaVersion"].getInt()
  result.kind = briefKindFromName(node["kind"].getStr())
  result.title = node["title"].getStr()
  result.sourceFile = node["sourceFile"].getStr()
  result.bodyMarkdown = node["bodyMarkdown"].getStr()
  result.reviewerSchemaVersion = node["reviewerSchemaVersion"].getInt()
  result.relatedBriefs = @[]
  for r in node["relatedBriefs"].items:
    result.relatedBriefs.add r.getStr()
  result.coversPreviews = @[]
  for c in node["coversPreviews"].items:
    result.coversPreviews.add coverageFromJson(c)
  result.captureViewports = @[]
  for v in node["captureViewports"].items:
    result.captureViewports.add viewportFromJson(v)
  result.scoringDimensions = @[]
  for d in node["scoringDimensions"].items:
    result.scoringDimensions.add dimensionFromJson(d)
  result.extra = initTable[string, string]()
  if "extra" in node:
    for k, v in node["extra"].pairs:
      result.extra[k] = v.getStr()

proc builtInBriefIndex*(): BriefIndex =
  ## Reconstruct the ``BriefIndex`` baked at build time. Returned by
  ## value so consumers can treat it as an immutable snapshot.
  result = BriefIndex(
    byBriefId: initOrderedTable[string, Brief](),
    byPreview: initOrderedTable[string, seq[string]](),
    errors: @[]
  )
  if BUILT_IN_BRIEF_INDEX_JSON.strip().len == 0:
    return
  let doc = parseJson(BUILT_IN_BRIEF_INDEX_JSON)
  for entry in doc["briefs"].items:
    let b = briefFromJson(entry)
    result.byBriefId[b.briefId] = b
  for previewId, briefIds in doc["byPreview"].pairs:
    var ids: seq[string] = @[]
    for id in briefIds.items:
      ids.add id.getStr()
    result.byPreview[previewId] = ids
  for e in doc["errors"].items:
    result.errors.add BriefIndexError(
      path: e["path"].getStr(),
      message: e["message"].getStr()
    )
"""
  writeFile(outPath, body)

proc resolveBriefsDir(arg: string): string =
  ## Resolve the ``--briefs`` argument to an absolute path. Empty
  ## string and ``-`` both signal "no briefs directory".
  if arg.len == 0 or arg == "-":
    return ""
  if arg.isAbsolute:
    return arg
  return absolutePath(arg)

when isMainModule:
  var briefsArg = ""
  var outPath = ""
  var p = initOptParser()
  while true:
    p.next()
    case p.kind
    of cmdEnd: break
    of cmdShortOption, cmdLongOption:
      case p.key
      of "briefs": briefsArg = p.val
      of "out": outPath = p.val
      else:
        echo "unknown option: --", p.key
        quit(1)
    of cmdArgument:
      echo "unexpected positional argument: ", p.key
      quit(1)

  if outPath.len == 0:
    echo "missing --out"
    quit(1)

  let briefsDir = resolveBriefsDir(briefsArg)
  var idx: BriefIndex
  if briefsDir.len > 0 and dirExists(briefsDir):
    idx = buildBriefIndex(briefsDir)
    echo "brief_index_build: indexed ", idx.byBriefId.len,
         " brief(s) from ", briefsDir, " (", idx.errors.len, " error(s))"
  else:
    idx = BriefIndex(
      byBriefId: initOrderedTable[string, Brief](),
      byPreview: initOrderedTable[string, seq[string]](),
      errors: @[]
    )
    if briefsArg.len == 0:
      echo "brief_index_build: no --briefs given; emitting empty index"
    else:
      echo "brief_index_build: ", briefsDir,
           " does not exist; emitting empty index"

  let payload = pretty(indexToJson(idx))
  emitStaticModule(payload, outPath)
  echo "brief_index_build: wrote ", outPath
