{
  description = "IsoNim - Isomorphic reactive web framework for Nim";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixpkgs-unstable";
    flake-utils.url = "github:numtide/flake-utils";
    git-hooks = {
      url = "github:cachix/git-hooks.nix";
      inputs.nixpkgs.follows = "nixpkgs";
    };
  };

  outputs =
    {
      self,
      nixpkgs,
      flake-utils,
      git-hooks,
    }:
    flake-utils.lib.eachDefaultSystem (
      system:
      let
        # ``claude-code-acp`` (now upstream-renamed to ``claude-agent-acp``)
        # depends on the unfree ``claude-code`` package; we therefore opt
        # in to unfree just for this dev shell.
        pkgs = import nixpkgs {
          inherit system;
          config.allowUnfree = true;
        };
        # Expose the binary under both the legacy ``claude-code-acp`` name
        # (which our Nim transport prefers via ``findExe``) and the new
        # ``claude-agent-acp`` name.
        claudeCodeAcp =
          pkgs.runCommand "claude-code-acp-compat"
            {
              nativeBuildInputs = [ pkgs.makeWrapper ];
            }
            ''
              mkdir -p $out/bin
              for bin in ${pkgs.claude-agent-acp}/bin/*; do
                ln -s "$bin" "$out/bin/$(basename "$bin")"
              done
              if [ ! -e $out/bin/claude-code-acp ]; then
                ln -s ${pkgs.claude-agent-acp}/bin/claude-agent-acp $out/bin/claude-code-acp
              fi
            '';
        # git-hooks.nix installs `.pre-commit-config.yaml` and git hooks into
        # `git rev-parse --show-toplevel` of the directory the shell is entered
        # from, so `nix develop /path/to/<this repo>` run inside another checkout
        # would plant this repository's hooks there. `ownRepoOnly` runs a snippet
        # only when that toplevel is this repository, recognised by a `flake.nix`
        # identical to the one this shell was evaluated from; anything it cannot
        # establish counts as another repository, so it fails safe.
        # tests/test_dev_shell_writes_nothing_elsewhere.sh
        ownRepoOnly = script: ''
          _own_repo_root="$(${pkgs.git}/bin/git rev-parse --show-toplevel 2>/dev/null || true)"
          if [ -n "$_own_repo_root" ] && [ -f "$_own_repo_root/flake.nix" ] \
            && [ "$(${pkgs.coreutils}/bin/sha256sum "$_own_repo_root/flake.nix" | ${pkgs.coreutils}/bin/cut -d' ' -f1)" \
              = "${builtins.hashFile "sha256" ./flake.nix}" ]; then
          ${script}
          # git-hooks.nix's installer leaves core.hooksPath as the RELATIVE
          # `.git/hooks`, in the config every worktree shares. A linked worktree
          # cannot resolve it (there `.git` is a file), so git silently runs no
          # hooks there. Point it at the common hooks directory instead.
          if [ "$(${pkgs.git}/bin/git config --local --get core.hooksPath 2>/dev/null)" = .git/hooks ]; then
            ${pkgs.git}/bin/git config --local core.hooksPath "$(${pkgs.git}/bin/git rev-parse --path-format=absolute --git-common-dir)/hooks"
          fi
          # The installer moves each Reprobuild hook dispatcher aside to
          # `<hook>.legacy` and puts pre-commit's shim in its slot, so the managed
          # hook (for pre-push, the publication gate) runs only by accident. Put the
          # dispatcher back and chain the shim as `<hook>.repro-local`, which the
          # dispatcher runs: the layout `repro hooks ensure --vcs` produces.
          _hooks="$(${pkgs.git}/bin/git rev-parse --path-format=absolute --git-path hooks 2>/dev/null || true)"
          for _legacy in "$_hooks"/*.legacy; do
            [ -f "$_legacy" ] && grep -q 'reprobuild hook dispatcher' "$_legacy" || continue
            _slot="''${_legacy%.legacy}"
            if [ -f "$_slot" ] && grep -q 'reprobuild hook dispatcher' "$_slot"; then
              rm -f "$_legacy"
            elif [ ! -e "$_slot" ] || grep -Eq '^# File generated by (pre-commit|prek)' "$_slot"; then
              if [ -f "$_slot.repro-local" ] && ! grep -Eq '^# File generated by (pre-commit|prek)' "$_slot.repro-local"; then
                echo "git-hooks: $_slot.repro-local is your own hook; run 'repro hooks ensure --vcs' to reconcile." >&2
                continue
              fi
              if [ -e "$_slot" ]; then mv -f "$_slot" "$_slot.repro-local"; fi
              mv -f "$_legacy" "$_slot"
            else
              echo "git-hooks: $_slot is not a pre-commit shim; run 'repro hooks ensure --vcs' to reconcile." >&2
            fi
          done
          unset _hooks _legacy _slot
          fi
          unset _own_repo_root
        '';

        # The repo's pre-commit hooks. Entering the default dev shell from inside
        # this repository writes the (gitignored) .pre-commit-config.yaml symlink
        # and installs them; CI's shared lint workflow runs the same set from this
        # shell.
        preCommit = git-hooks.lib.${system}.run {
          src = ./.;
          hooks = {
            check-added-large-files.enable = true;
            check-merge-conflicts.enable = true;
            lint = {
              enable = true;
              name = "just lint";
              entry = "just lint";
              language = "system";
              pass_filenames = false;
            };
          };
        };
      in
      {
        devShells.default = pkgs.mkShell {
          packages =
            (with pkgs; [
              nim
              nimble
              nodejs
              # TBAR-M5b: yarn 1 manages the editor's runtime JS deps
              # (``@tiptap/core``, ``@tiptap/starter-kit``, ``tiptap-markdown``,
              # ``xterm``).  The editor-vendor Nix derivation calls
              # ``yarn install --offline`` against ``fetchYarnDeps`` to
              # produce the UMD bundles consumed by ``editor-build``.
              yarn
              # TBAR-M5b: esbuild bundles the per-library entry scripts
              # into UMD ``globalThis``-attaching bundles. Available
              # for use both inside the Nix derivation and from the dev
              # shell when debugging the bundling step.
              esbuild
              # TBAR-M5b: pre-fetch yarn deps for the Nix derivation
              # via ``prefetch-yarn-deps`` (used to compute the
              # ``fetchYarnDeps`` hash when ``yarn.lock`` changes).
              prefetch-yarn-deps
              just
              # REV-M3: userspace PostgreSQL substrate.  ``postgresql_16``
              # provides ``initdb``, ``postgres``, ``psql``, ``pg_isready``,
              # ``pg_dump``, ``pg_restore`` on $PATH.  ``process-compose``
              # orchestrates the local dev cluster (see process-compose.yaml).
              postgresql_16
              process-compose
              # Phase A: ACP-speaking Claude Code adapter. Exposes both
              # ``claude-code-acp`` (legacy/expected name) and
              # ``claude-agent-acp`` (current upstream name) on $PATH.
              claudeCodeAcp
              # Codex-backed ACP adapter — sibling backend selectable
              # via ``[agent].backend = "codex"`` in the review config
              # (or the ``--agent-backend=codex`` CLI flag). Lives on
              # PATH alongside claude-agent-acp so users can switch
              # without re-entering the shell.
              codex-acp
            ])
            # ``chromium`` and ``chromedriver`` only build on Linux in
            # nixpkgs; Darwin users supply system Chrome / a Homebrew
            # chromedriver. Gate them here so ``nix develop`` works on
            # macOS too.
            ++ pkgs.lib.optionals pkgs.stdenv.isLinux (
              with pkgs;
              [
                chromium
                chromedriver
              ]
            );

          shellHook = ''
            ${ownRepoOnly preCommit.shellHook}
            echo "IsoNim dev shell — nim $(nim --version 2>&1 | head -1), node $(node --version)"
            # REV-M3 dev-cluster defaults; users may override in their own
            # .envrc (see .envrc.example).
            export ISONIM_REVIEW_PGDATA="''${ISONIM_REVIEW_PGDATA:-$PWD/.dev/postgres}"
            export ISONIM_REVIEW_PGPORT="''${ISONIM_REVIEW_PGPORT:-5533}"
          '';
        };

        packages.nginx-module = pkgs.callPackage ./nix/nginx-module.nix { };

        # TBAR-M5b: vendored UMD bundles for the editor's TipTap + xterm
        # runtime deps.  Output: ``$out/{tiptap,xterm}.umd.js`` +
        # ``$out/MANIFEST.txt``.  Consumed by the ``editor-build`` recipe
        # in ``isonim-examples/Justfile`` via ``nix build --print-out-paths
        # ~/metacraft/isonim#editor-vendor`` + ``cp -L``.
        packages.editor-vendor = pkgs.callPackage ./nix/editor-vendor.nix { };
      }
    );
}
