## isonim/dsl/tailwind.nim
##
## Compile-time Tailwind CSS class resolver.
##
## Loads the style mapping generated by the real Tailwind CSS CLI
## (via tools/tailwind-extract.mjs) and expands class strings to
## (CSS-property, value) pairs at compile time.
##
## Build pipeline:
##   1. `node tools/tailwind-extract.mjs` — runs Tailwind CSS, produces
##      build/tailwind.css (for web) and build/tailwind-styles.json (for native)
##   2. This module loads tailwind-styles.json at Nim compile time
##   3. The buildHtml macro calls expandTailwindClasses() to expand class
##      attributes to setStyle calls
##
## On web (-d:js), class attributes pass through to the browser
## where build/tailwind.css provides the styles.

import std/[json, tables, strutils, os]

# ===========================================================================
# Load the Tailwind style map at compile time from the JSON file
# ===========================================================================

const tailwindJsonPath = currentSourcePath().parentDir().parentDir().parentDir().parentDir() /
                          "build" / "tailwind-styles.json"

when fileExists(tailwindJsonPath):
  const tailwindJsonStr = staticRead(tailwindJsonPath)
  const hasTailwindStyles* = true
else:
  const tailwindJsonStr = "{}"
  const hasTailwindStyles* = false

proc buildStyleMap(): Table[string, seq[tuple[prop, val: string]]] {.compileTime.} =
  let j = parseJson(tailwindJsonStr)
  for className, propsNode in j:
    var styles: seq[tuple[prop, val: string]]
    for prop, val in propsNode:
      styles.add((prop, val.getStr()))
    result[className] = styles

const tailwindStyles* = buildStyleMap()

# ===========================================================================
# Public API — called by the DSL macro at compile time
# ===========================================================================

proc parseTailwindClass*(cls: string): seq[tuple[prop, val: string]] =
  ## Look up a single Tailwind utility class in the style map.
  ## Returns empty seq for unrecognized classes.
  if cls in tailwindStyles:
    tailwindStyles[cls]
  else:
    @[]

proc expandTailwindClasses*(classStr: string): seq[tuple[prop, val: string]] =
  ## Parse a space-separated Tailwind class string and expand all utilities
  ## to CSS property/value pairs. Unrecognized classes are silently skipped.
  for cls in classStr.splitWhitespace():
    let styles = parseTailwindClass(cls)
    result.add(styles)

proc expandTailwindClassesCompileTime*(classStr: string): seq[tuple[prop, val: string]]
    {.compileTime.} =
  ## Compile-time version for use inside macros.
  for cls in classStr.splitWhitespace():
    if cls in tailwindStyles:
      result.add(tailwindStyles[cls])
