## isonim/dsl/tailwind.nim
##
## Compile-time Tailwind CSS class resolver.
##
## Loads the style mapping generated by the real Tailwind CSS CLI
## (via tools/tailwind-extract.mjs) and expands class strings to
## (CSS-property, value) pairs at compile time.
##
## Build pipeline:
##   1. `node tools/tailwind-extract.mjs` — runs Tailwind CSS, produces
##      build/tailwind.css (for web) and build/tailwind-styles.json (for native)
##   2. This module loads tailwind-styles.json at Nim compile time
##   3. The ui macro calls expandTailwindClasses() to expand class
##      attributes to setStyle calls
##
## On web (-d:js), class attributes pass through to the browser
## where build/tailwind.css provides the styles.

import std/[json, tables, strutils, os]

# ===========================================================================
# Load the Tailwind style map at compile time from the JSON file
# ===========================================================================

## Each consuming app drives its own extract so the content-scan set covers
## that app's source.  Pass an absolute path via
## ``-d:tailwindStylesPathOverride=<path>`` (preferred) when invoking nim;
## the empty default falls back to isonim's own ``build/`` so isonim's own
## dev/test compiles keep working without the flag.
const tailwindStylesPathOverride* {.strdefine.}: string = ""

const defaultTailwindJsonPath = block:
  const path = currentSourcePath().replace('\\', '/')
  path.parentDir().parentDir().parentDir().parentDir() / "build" / "tailwind-styles.json"

const tailwindJsonPath =
  if tailwindStylesPathOverride.len > 0: tailwindStylesPathOverride
  else: defaultTailwindJsonPath

when defined(nimscript) or defined(js):
  # fileExists not available at compile time for JS target
  const tailwindJsonStr = static:
    try: staticRead(tailwindJsonPath)
    except: "{}"
  const hasTailwindStyles* = tailwindJsonStr != "{}"
else:
  when fileExists(tailwindJsonPath):
    const tailwindJsonStr = staticRead(tailwindJsonPath)
    const hasTailwindStyles* = true
  else:
    const tailwindJsonStr = "{}"
    const hasTailwindStyles* = false

proc buildStyleMap(): tuple[
    styles: Table[string, seq[tuple[prop, val: string]]];
    variants: Table[string, string];
    units: Table[string, seq[tuple[prop, unit: string]]]
] {.compileTime.} =
  let j = parseJson(tailwindJsonStr)
  for className, propsNode in j:
    var styles: seq[tuple[prop, val: string]]
    for prop, val in propsNode:
      if prop == "variant":
        result.variants[className] = val.getStr()
      elif prop == "units":
        for uprop, uval in val:
          result.units.mgetOrPut(className, @[]).add((uprop, uval.getStr()))
      else:
        styles.add((prop, val.getStr()))
    result.styles[className] = styles

const tailwindMap = buildStyleMap()
const tailwindStyles* = tailwindMap.styles
const tailwindVariants* = tailwindMap.variants
  ## Variants mode: class name → variant (`sm`, `dark`, `hover`), only for entries the
  ## extractor tagged with `--variants`. Empty without the flag.
const tailwindUnits* = tailwindMap.units
  ## Variants mode: class name → stripped `px` units per prop. Empty without the flag.

# ===========================================================================
# Public API — called by the DSL macro at compile time
# ===========================================================================

proc parseTailwindClass*(cls: string): seq[tuple[prop, val: string]] =
  ## Look up a single Tailwind utility class in the style map.
  ## Returns empty seq for unrecognized classes.
  if cls in tailwindStyles:
    tailwindStyles[cls]
  else:
    @[]

proc expandTailwindClasses*(classStr: string): seq[tuple[prop, val: string]] =
  ## Parse a space-separated Tailwind class string and expand all utilities
  ## to CSS property/value pairs. Unrecognized classes are silently skipped.
  for cls in classStr.splitWhitespace():
    let styles = parseTailwindClass(cls)
    result.add(styles)

when defined(isonimTailwindVariants):
  proc isBareNumber(s: string): bool {.compileTime.} =
    ## True when the extractor's px-strip pattern could have produced `s`
    ## (`^[\d.]+$`, mirroring `tailwind-extract.mjs`), so a recorded unit
    ## may be appended.
    if s.len == 0:
      return false
    for c in s:
      if c notin {'0' .. '9', '.'}:
        return false
    return true

proc expandTailwindClassesCompileTime*(classStr: string): seq[tuple[prop, val: string]]
    {.compileTime.} =
  ## Compile-time version for use inside macros.
  when defined(isonimTailwindVariants):
    # Variants opt-in: the switch is the global `-d:isonimTailwindVariants`
    # the email build sets in config.nims — not a per-renderer hook
    # like the static vocabulary — because the expansion runs once at macro-expansion
    # time, before any renderer type is known.
    for cls in classStr.splitWhitespace():
      if cls in tailwindStyles:
        var prefix = ""
        if cls in tailwindVariants:
          prefix = "@" & tailwindVariants[cls] & ":"
        for (prop, val) in tailwindStyles[cls]:
          var v = val
          if isBareNumber(v) and cls in tailwindUnits:
            for u in tailwindUnits[cls]:
              if u.prop == prop:
                v = v & u.unit
                break
          result.add((prefix & prop, v))
  else:
    for cls in classStr.splitWhitespace():
      if cls in tailwindStyles:
        result.add(tailwindStyles[cls])
