## Follow-up 3 — ``isonim-review seed-run`` end-to-end tests.
##
## Drives the real ``isonim-review`` binary against an ephemeral
## ``PgFixture`` and a synthetic workspace.  Each test seeds a run
## from one or more fixture PNGs, then asserts the rows in
## ``design_review.runs`` / ``design_review.captures`` and the bytes
## on disk under the configured capture store.
##
## The final ``e2e_seed_run_then_run_review`` test rounds the loop:
## after seeding the run it invokes ``run-review --run <id>
## --agent-backend canned`` and checks the agent-report row lands
## in the DB.  That exercises the ``briefAtRevision`` seeded
## fallback in the path that production reviews take.

import std/[json, os, osproc, streams, strtabs, strutils, times, unittest]

import db_connector/db_postgres

import isonim/editor/design_review/brief_at_revision

import helpers/design_review_pg_fixture

# --------------------------------------------------------------------------- #
#  Helpers.
# --------------------------------------------------------------------------- #

const RepoRootHere = currentSourcePath().parentDir().parentDir()
const IsonimReviewBin = RepoRootHere / "build" / "bin" / "isonim-review"

proc shouldHave(path: string) =
  if not fileExists(path):
    raise newException(IOError,
      "test_design_review_cli_seed_run: binary not found at " & path &
      ".  Build it with `just isonim-review-build`.")

proc tmpWs(suffix: string): string =
  result = getTempDir() / ("isonim_seed_run_" & suffix & "_" &
                            $epochTime().int)
  removeDir(result)
  createDir(result)

const FixtureBriefYaml = """---
briefId: render.task-app
schemaVersion: 1
kind: render
title: Task App
coversPreviews:
  - storyRef: { group: G, name: N, kind: page, index: 0 }
    backends: [web, tui, gpui, freya, cocoa, android, ios]
captureViewports:
  - { width: 1080, height: 720, label: tablet }
reviewerSchemaVersion: 1
scoringDimensions:
  - { id: a, label: A, weight: 1.0, scale: { min: 0, max: 10 } }
---
SEEDED_BRIEF_BODY_MARKER
"""

proc seedWorkspace(ws: string) =
  ## Write a brief into ``ws/briefs/render/task-app.md`` — no git
  ## init / manifest XML required for the seeded path.
  createDir(ws / "briefs" / "render")
  writeFile(ws / "briefs" / "render" / "task-app.md", FixtureBriefYaml)

proc writeConfig(workspaceRoot, storePath: string; pgPort: int): string =
  let cfgPath = workspaceRoot / "config.toml"
  writeFile(cfgPath,
    "[db]\nhost = \"127.0.0.1\"\nport = " & $pgPort &
    "\ndatabase = \"isonim_design_review\"\n" &
    "url = \"postgres://design_review_app@127.0.0.1:" & $pgPort &
    "/isonim_design_review\"\n" &
    "[store]\npath = \"" & storePath & "\"\n" &
    "[workspace]\nroot = \"" & workspaceRoot & "\"\n")
  cfgPath

proc runIsonimReview(args: seq[string]; cwd: string):
                     tuple[exitCode: int; stdout, stderr: string] =
  var environ = newStringTable(modeCaseSensitive)
  for kv in envPairs():
    environ[kv.key] = kv.value
  let p = startProcess(IsonimReviewBin, args = args,
                       workingDir = cwd, env = environ,
                       options = {poUsePath})
  let code = p.waitForExit()
  let so = p.outputStream.readAll()
  let se = p.errorStream.readAll()
  p.close()
  (exitCode: code, stdout: so, stderr: se)

proc openAppConn(pgPort: int): DbConn =
  open("", "design_review_app", "",
       "host=127.0.0.1 port=" & $pgPort &
       " dbname=isonim_design_review user=design_review_app")

proc openMigConn(pgPort: int): DbConn =
  open("", "design_review_migrator", "",
       "host=127.0.0.1 port=" & $pgPort &
       " dbname=isonim_design_review user=design_review_migrator")

# A 1x1 RGBA PNG (synthetic; just enough to pass the PNG signature +
# IHDR validation in cmd_seed_run.validatePng).  Generated by hand
# rather than via the in-tree png_codec to keep the test independent
# of that module's encoder.
const PngOnePx = [
  byte(0x89), byte(0x50), byte(0x4E), byte(0x47),
  byte(0x0D), byte(0x0A), byte(0x1A), byte(0x0A),
  # IHDR length=13
  byte(0x00), byte(0x00), byte(0x00), byte(0x0D),
  byte('I'), byte('H'), byte('D'), byte('R'),
  # width = 1
  byte(0x00), byte(0x00), byte(0x00), byte(0x01),
  # height = 1
  byte(0x00), byte(0x00), byte(0x00), byte(0x01),
  # bit depth 8, color type 6 (RGBA), compression 0, filter 0, interlace 0
  byte(0x08), byte(0x06), byte(0x00), byte(0x00), byte(0x00),
  # IHDR CRC (computed: 0x1F15C489)
  byte(0x1F), byte(0x15), byte(0xC4), byte(0x89),
  # IDAT length=16
  byte(0x00), byte(0x00), byte(0x00), byte(0x10),
  byte('I'), byte('D'), byte('A'), byte('T'),
  # zlib stream (stored block, 4 bytes raw: filter byte + RGBA pixel)
  byte(0x78), byte(0x01), byte(0x01), byte(0x05), byte(0x00),
  byte(0xFA), byte(0xFF), byte(0x00), byte(0xFF), byte(0x00),
  byte(0x00), byte(0xFF), byte(0x00), byte(0x09), byte(0x00),
  byte(0x04),
  # IDAT CRC (not validated by our codec — pad with zeros)
  byte(0x00), byte(0x00), byte(0x00), byte(0x00),
  # IEND length=0
  byte(0x00), byte(0x00), byte(0x00), byte(0x00),
  byte('I'), byte('E'), byte('N'), byte('D'),
  # IEND CRC
  byte(0xAE), byte(0x42), byte(0x60), byte(0x82),
]

proc writePngFixture(ws: string; backend: string; tag: int): string =
  ## Write a unique PNG for ``backend`` to ``ws/png/<backend>.png``.
  ## ``tag`` is mixed into one byte of the PNG payload to keep each
  ## fixture's sha256 distinct so we exercise the content-addressed
  ## store on a real branch.
  createDir(ws / "png")
  let path = ws / "png" / (backend & ".png")
  var bytes = newSeq[byte](PngOnePx.len)
  for i in 0 ..< PngOnePx.len: bytes[i] = PngOnePx[i]
  # Mutate the IDAT payload byte — survives the validatePng signature
  # check (only the first 24 bytes are inspected) and makes the sha
  # different per file.
  bytes[44] = byte(tag and 0xFF)
  var asStr = newString(bytes.len)
  for i in 0 ..< bytes.len: asStr[i] = char(bytes[i])
  writeFile(path, asStr)
  path

# --------------------------------------------------------------------------- #
#  Tests.
# --------------------------------------------------------------------------- #

proc lastNonEmpty(s: string): string =
  for line in s.splitLines():
    let stripped = line.strip()
    if stripped.len > 0:
      result = stripped

suite "Follow-up 3 — isonim-review seed-run":

  setup:
    shouldHave(IsonimReviewBin)

  test "test_seed_run_creates_run_and_captures":
    ## Three different PNGs for three backends produce one run row +
    ## three captures rows, all addressed by their sha256 in the
    ## content-addressed store.
    let pgf = newPgFixture()
    defer: pgf.shutdown()
    let ws = tmpWs("create")
    defer: removeDir(ws)
    seedWorkspace(ws)
    let storePath = ws / "review-store"
    let cfg = writeConfig(ws, storePath, pgf.port)

    let webPng = writePngFixture(ws, "web", 1)
    let tuiPng = writePngFixture(ws, "tui", 2)
    let androidPng = writePngFixture(ws, "android", 3)

    let res = runIsonimReview(@[
      "seed-run", "--brief", "render.task-app",
      "--capture", "web=" & webPng,
      "--capture", "tui=" & tuiPng,
      "--capture", "android=" & androidPng,
      "--workspace", ws,
      "--project", ws,
      "--config", cfg], cwd = ws)
    if res.exitCode != 0:
      echo "stdout:\n" & res.stdout
      echo "stderr:\n" & res.stderr
    check res.exitCode == 0

    let runId = lastNonEmpty(res.stdout)
    check runId.len == 36   # UUID

    let migConn = openMigConn(pgf.port)
    defer: migConn.close()
    let nRuns = parseInt(migConn.getValue(sql(
      "SELECT count(*) FROM design_review.runs " &
      "WHERE run_id = '" & runId & "'::uuid")))
    check nRuns == 1
    let nCaps = parseInt(migConn.getValue(sql(
      "SELECT count(*) FROM design_review.captures " &
      "WHERE run_id = '" & runId & "'::uuid")))
    check nCaps == 3

    # The three captures must each be content-addressed under the
    # configured store path.
    for backend in ["web", "tui", "android"]:
      let pngPath = migConn.getValue(sql(
        "SELECT png_path FROM design_review.captures " &
        "WHERE run_id = '" & runId & "'::uuid AND backend = '" &
        backend & "'"))
      check pngPath.startsWith(storePath)
      check fileExists(pngPath)

  test "test_seed_run_rejects_missing_png":
    ## Non-existent PNG path → non-zero exit + no DB rows.
    let pgf = newPgFixture()
    defer: pgf.shutdown()
    let ws = tmpWs("missing")
    defer: removeDir(ws)
    seedWorkspace(ws)
    let storePath = ws / "review-store"
    let cfg = writeConfig(ws, storePath, pgf.port)

    let res = runIsonimReview(@[
      "seed-run", "--brief", "render.task-app",
      "--capture", "web=" & ws / "does-not-exist.png",
      "--workspace", ws,
      "--project", ws,
      "--config", cfg], cwd = ws)
    check res.exitCode != 0

    let migConn = openMigConn(pgf.port)
    defer: migConn.close()
    let nRuns = parseInt(migConn.getValue(sql(
      "SELECT count(*) FROM design_review.runs")))
    check nRuns == 0

  test "test_seed_run_rejects_non_png_file":
    ## A text file masquerading as a PNG is caught by validatePng's
    ## signature check.  Exit non-zero, message mentions "not a valid PNG".
    let pgf = newPgFixture()
    defer: pgf.shutdown()
    let ws = tmpWs("textfile")
    defer: removeDir(ws)
    seedWorkspace(ws)
    let storePath = ws / "review-store"
    let cfg = writeConfig(ws, storePath, pgf.port)

    let fakePng = ws / "fake.png"
    writeFile(fakePng, "this is not a PNG, sorry!\n")

    let res = runIsonimReview(@[
      "seed-run", "--brief", "render.task-app",
      "--capture", "web=" & fakePng,
      "--workspace", ws,
      "--project", ws,
      "--config", cfg], cwd = ws)
    check res.exitCode != 0
    check (res.stdout & res.stderr).contains("not a valid PNG")

    let migConn = openMigConn(pgf.port)
    defer: migConn.close()
    let nRuns = parseInt(migConn.getValue(sql(
      "SELECT count(*) FROM design_review.runs")))
    check nRuns == 0

  test "test_seed_run_uses_seeded_manifest_hash":
    ## The run's ``manifest_hash`` column must start with ``seeded:``
    ## and embed the operator-supplied tag.
    let pgf = newPgFixture()
    defer: pgf.shutdown()
    let ws = tmpWs("hash")
    defer: removeDir(ws)
    seedWorkspace(ws)
    let storePath = ws / "review-store"
    let cfg = writeConfig(ws, storePath, pgf.port)
    let webPng = writePngFixture(ws, "web", 7)

    let res = runIsonimReview(@[
      "seed-run", "--brief", "render.task-app",
      "--capture", "web=" & webPng,
      "--manifest-hash-tag", "m-evp-14-historical",
      "--workspace", ws,
      "--project", ws,
      "--config", cfg], cwd = ws)
    check res.exitCode == 0
    let runId = lastNonEmpty(res.stdout)

    let migConn = openMigConn(pgf.port)
    defer: migConn.close()
    let hash = migConn.getValue(sql(
      "SELECT manifest_hash FROM design_review.runs " &
      "WHERE run_id = '" & runId & "'::uuid"))
    check hash == "seeded:m-evp-14-historical"
    check isSeededManifestHash(hash)

  test "test_brief_at_revision_falls_back_for_seeded_run":
    ## With ``manifestHash = "seeded:foo"`` the resolver must read the
    ## brief straight from the working tree — no manifest XML, no
    ## ``git show`` plumbing required.
    let ws = tmpWs("bav")
    defer: removeDir(ws)
    seedWorkspace(ws)
    let body = briefAtRevision(ws, "seeded:foo", "render.task-app")
    check body.contains("SEEDED_BRIEF_BODY_MARKER")
    check body.contains("briefId: render.task-app")

  test "e2e_seed_run_then_run_review":
    ## Full loop: seed seven backends, then drive run-review against
    ## a canned reviewer output.  Assert the agent_report row lands
    ## in the DB.
    let pgf = newPgFixture()
    defer: pgf.shutdown()
    let ws = tmpWs("e2e")
    defer: removeDir(ws)
    seedWorkspace(ws)
    let storePath = ws / "review-store"
    let cfg = writeConfig(ws, storePath, pgf.port)

    var captureArgs: seq[string] = @["seed-run",
      "--brief", "render.task-app"]
    var tag = 10
    for backend in ["web", "tui", "gpui", "freya", "cocoa",
                    "android", "ios"]:
      let pngPath = writePngFixture(ws, backend, tag)
      inc tag
      captureArgs.add "--capture"
      captureArgs.add backend & "=" & pngPath
    captureArgs.add "--workspace"; captureArgs.add ws
    captureArgs.add "--project"; captureArgs.add ws
    captureArgs.add "--config"; captureArgs.add cfg

    let seed = runIsonimReview(captureArgs, cwd = ws)
    if seed.exitCode != 0:
      echo "seed stdout:\n" & seed.stdout
      echo "seed stderr:\n" & seed.stderr
    check seed.exitCode == 0
    let runId = lastNonEmpty(seed.stdout)

    let migConn = openMigConn(pgf.port)
    defer: migConn.close()
    let nCaps = parseInt(migConn.getValue(sql(
      "SELECT count(*) FROM design_review.captures " &
      "WHERE run_id = '" & runId & "'::uuid")))
    check nCaps == 7

    # Canned reviewer output — schema matches the e2e_run_review tests.
    let cannedPath = ws / "canned.md"
    let cannedBody = "---\n" &
      "reviewerSchemaVersion: 1\n" &
      "briefId: render.task-app\n" &
      "runId: " & runId & "\n" &
      "agentName: canned\n" &
      "agentVersion: v1\n" &
      "manifestHash: seeded:test\n" &
      "capturedAt: 2026-05-19T11:32:04Z\n" &
      "overall:\n  score: 8.0\n  status: pass\n" &
      "previews:\n" &
      "  \"G/N:page#0@web\":\n" &
      "    scores: { a: 8 }\n" &
      "    status: pass\n" &
      "    defects: []\n" &
      "---\nbody\n"
    writeFile(cannedPath, cannedBody)

    let review = runIsonimReview(@[
      "run-review", "--run", runId,
      "--agent-backend", "canned",
      "--canned-path", cannedPath,
      "--agent-name", "canned",
      "--agent-version", "v1",
      "--workspace", ws,
      "--project", ws,
      "--config", cfg], cwd = ws)
    if review.exitCode != 0:
      echo "review stdout:\n" & review.stdout
      echo "review stderr:\n" & review.stderr
    check review.exitCode == 0

    let nReports = parseInt(migConn.getValue(sql(
      "SELECT count(*) FROM design_review.agent_reports " &
      "WHERE run_id = '" & runId & "'::uuid")))
    check nReports == 1

    let parsed = parseJson(migConn.getValue(sql(
      "SELECT parsed_scores::text FROM design_review.agent_reports " &
      "WHERE run_id = '" & runId & "'::uuid")))
    check parsed["overall"]["status"].getStr == "pass"

    let rawPath = storePath / "reports" / runId / "canned.md"
    check fileExists(rawPath)
