## isonim/web/hmr_component.nim
##
## The `{.uiComponent.}` pragma macro and the runtime that backs it.
## Active machinery only under `-d:isonimHmr`; without the flag the
## pragma is a no-op and component calls are direct proc calls.
##
## Usage:
##
##   import isonim
##   import isonim/web/hmr_component
##
##   proc childA(): Node {.uiComponent.} =
##     ui(r): span: text "A"
##
##   proc app(): Node {.uiComponent.} =
##     ui(r): div: childA()
##
##   # Parametric components (v2) — components that take args:
##   proc panel(r: WebRenderer; vm: PanelVM): Node {.uiComponent.} =
##     ui(r):
##       div: text vm.title.val
##
##   when defined(isonimHmr):
##     bootstrapHmr()
##
## See `codetracer-specs/Front-Ends/IsoNim/Hot-Module-Reload.md` for the
## full design rationale.

import std/macros

when defined(isonimHmr) and defined(js):
  import std/[jsffi, tables]
  import isonim/web/dom_api
  import isonim/web/hmr_ui_registry
  import isonim/core/[signals, computation, owner]
  export hmr_ui_registry  # so users get hmrRegisterFactory etc. from one import

  # ---------------------------------------------------------------------------
  # Parametric component runtime
  #
  # Zero-arg `{.uiComponent.}` procs go through `hmrInvokeComponent` (per-slot
  # memo). Parametric procs (`proc Name(args...): T`) cannot use a per-slot
  # memo — the same slot is reachable from multiple call sites with different
  # args, and a single memo would be either incorrect (returns a stale Node
  # for a different arg set) or a deopt (re-computes always but at the cost of
  # the memo machinery). So parametric components use a thinner dispatch path:
  # read `slot.factory.val` (subscribes to swaps) and call through to the
  # current factory. The reactive boundary that gives DOM-identity preservation
  # in v2 is `mountUiHot`, not the call site.
  # ---------------------------------------------------------------------------

  proc newJsArray*(): JsObject =
    ## Returns an empty JS array as a JsObject. Used by the parametric
    ## dispatch to package args before invoking the slot factory via
    ## `Function.prototype.apply`. We use a small `{.emit.}` body
    ## because `importjs: "[]"` is rejected as a pattern with no
    ## placeholders.
    {.emit: [result, " = [];"].}

  proc jsArrayPush*(arr, item: JsObject) =
    ## Appends `item` to the JS array. Caller is responsible for
    ## wrapping raw values in `toJs`.
    {.emit: [arr, ".push(", item, ");"].}

  proc applyJsFunction*(fn, argsArr: JsObject): JsObject =
    ## Invokes `fn` (a JS function value) with the given args array.
    ## Equivalent to `fn(...argsArr)`. We use `apply` rather than
    ## spread syntax so this stays compatible with any JS engine the
    ## bundle might be evaluated in.
    {.emit: [result, " = ", fn, ".apply(null, ", argsArr, ");"].}

  proc hmrInvokeParametric*(loc: string; args: JsObject): JsObject =
    ## Runtime entry point for parametric `{.uiComponent.}` calls.
    ##
    ## - Looks up the slot at `loc` and asserts it has been registered.
    ##   Missing slots indicate a registration ordering bug (the
    ##   `{.uiComponent.}` pragma should have emitted a top-level
    ##   `hmrRegisterFactory` call that ran during module init).
    ## - Marks the slot as claimed in the current generation so it
    ##   survives the next prune sweep.
    ## - Reads `slot.factory.val` so the calling reactive scope
    ##   subscribes to slot swaps. When the factory signal is rewritten
    ##   (because a hash change made the slot factory update on bundle
    ##   reload) the surrounding render effect — typically the one set
    ##   up by `mountUiHot` — re-runs and the DOM is reconciled.
    ## - Calls the current factory with the supplied args and returns
    ##   the JsObject result. The dispatch proc generated by the
    ##   `{.uiComponent.}` macro applies a typed `.to(T)` to coerce the
    ##   result back to the user-declared return type.
    ##
    ## Errors raised inside the factory propagate to the caller. The
    ## `mountUiHot` boundary is responsible for catching them so the
    ## previous DOM stays intact across a failed swap. We also surface
    ## the error through `globalUiOnError` for transports / overlays.
    ensureUiRegistry()
    let reg = globalUiRegistry
    let slot = reg.entries.getOrDefault(loc)
    if slot == nil:
      raise newException(Defect,
        "HMR: no factory registered for parametric component at " & loc &
        ". The {.uiComponent.} pragma should have emitted a top-level " &
        "registration. If you're seeing this, the registration block " &
        "didn't run — typically because the module containing the " &
        "component wasn't imported/evaluated.")
    slot.claimedGen = reg.currentGen
    let factoryProc = slot.factory.val
    try:
      return applyJsFunction(factoryProc, args)
    except Exception as err:
      if globalUiOnError != nil:
        globalUiOnError(loc, err)
      raise

  proc hmrInvokeComponent*(loc: string): Node =
    ## Runtime entry point inserted at every component-call site by the
    ## `{.uiComponent.}` pragma. Looks up the slot (must have been
    ## registered at module init by the pragma's emitted top-level
    ## block), gets its memo (creating once on first use under the
    ## persistent HMR owner so it survives outer-effect re-runs), and
    ## returns the cached Node.
    ensureUiRegistry()
    let reg = globalUiRegistry
    let slot = reg.entries.getOrDefault(loc)
    if slot == nil:
      raise newException(Defect,
        "HMR: no factory registered for component at " & loc &
        ". The {.uiComponent.} pragma should have emitted a top-level " &
        "registration. If you're seeing this, the registration block " &
        "didn't run — typically because the module containing the " &
        "component wasn't imported/evaluated.")
    slot.claimedGen = reg.currentGen
    if not slot.hasMemo:
      runWithOwner(reg.persistentOwner, proc() =
        slot.memo = createMemo(proc(): Node =
          # The slot stores the user's body proc as a JsObject (type
          # erased so all slots share one registry entry shape). Cast
          # back to the typed proc we know it is and call.
          let factoryProc = slot.factory.val.to(proc(): Node)
          try:
            let n = factoryProc()
            slot.lastGoodNode = n
            return n
          except Exception as err:
            # Contain the failure at the memo boundary: report and return
            # the most recent good Node. Returning the same ref makes
            # insertExpression's pointer-equality short-circuit kick in,
            # so the DOM doesn't mutate. If we don't have a prior good
            # Node yet (initial render also threw), there's nothing to
            # short-circuit to — re-raise.
            if globalUiOnError != nil:
              globalUiOnError(loc, err)
            if slot.lastGoodNode != nil:
              return slot.lastGoodNode
            raise)
      )
      slot.hasMemo = true
    slot.memo.val

  proc buildParametricDispatch(realName, locLit, returnType: NimNode;
                                argNames: seq[NimNode]): NimNode =
    ## Build the body of a parametric dispatch proc:
    ##
    ##   let _hmrArgs = newJsArray()
    ##   jsArrayPush(_hmrArgs, toJs(arg1))
    ##   jsArrayPush(_hmrArgs, toJs(arg2))
    ##   ...
    ##   cast[<ReturnType>](hmrInvokeParametric(<locStr>, _hmrArgs))
    ##
    ## We use `cast` rather than `.to(T)` for the JS→Nim coercion at the
    ## end. `to(JsObject, typedesc)` from std/jsffi resolves to the wrong
    ## overload in this macro-generated context (the typedesc travels as
    ## a value argument), and on the JS backend `cast[T](jsObj)` is a
    ## type-only assertion — the same machine code as `.to(T)` would
    ## have produced. `realName` is unused here (the caller assembles
    ## the proc with this body) but kept in the signature for symmetry
    ## with future variants.
    let argsVar = genSym(nskLet, "hmrArgs")
    var body = newStmtList()
    body.add(newLetStmt(argsVar, newCall(bindSym"newJsArray")))
    for arg in argNames:
      body.add(newCall(bindSym"jsArrayPush", argsVar,
                        newCall(bindSym"toJs", arg)))
    let invocation = newCall(bindSym"hmrInvokeParametric", locLit, argsVar)
    let coerce = newTree(nnkCast, returnType, invocation)
    body.add(coerce)
    body

  proc cloneParamsWithFreshNames(params: NimNode): (NimNode, seq[NimNode]) =
    ## Copy a `nnkFormalParams` node, replacing parameter-name symbols
    ## with fresh untyped idents (so the new proc binds them as its own
    ## locals when type-checked). Type and default nodes are copied as
    ## subtrees — type sym refs resolve back to the same types when the
    ## generated dispatch is checked in the caller's scope. Returns the
    ## new params node and the list of fresh argument idents in
    ## declaration order.
    let cloned = newTree(nnkFormalParams)
    cloned.add(params[0].copyNimTree)  # return type slot
    var argNames: seq[NimNode] = @[]
    for i in 1 ..< params.len:
      let identDef = params[i]
      doAssert identDef.len >= 3,
        "uiComponent: malformed parameter definition"
      let typeNode = identDef[identDef.len - 2].copyNimTree
      let defaultNode = identDef[identDef.len - 1].copyNimTree
      for j in 0 ..< identDef.len - 2:
        let originalName = identDef[j]
        let freshName = ident($originalName)
        argNames.add(freshName)
        cloned.add(newIdentDefs(freshName, typeNode.copyNimTree,
                                defaultNode.copyNimTree))
    (cloned, argNames)

  macro uiComponentTyped(realName: untyped;
                          procDef: typed): untyped =
    ## Stage 2 of the `{.uiComponent.}` pragma: receives the proc def
    ## with name resolved (typed), so `symBodyHash` can compute the
    ## transitive content hash of its body. Generates two flavours of
    ## dispatch:
    ##
    ## - Zero-arg (`proc Name(): Node`) → memoised dispatch through
    ##   `hmrInvokeComponent`. The per-slot memo means a parent reactive
    ##   effect re-running for unrelated reasons gets the cached Node
    ##   back, preserving DOM identity. This is the original v1 path.
    ##
    ## - Parametric (`proc Name(args...): T`) → unmemoised dispatch
    ##   through `hmrInvokeParametric`. The same slot is reachable from
    ##   multiple call sites with different args, so a per-slot memo
    ##   would be wrong. DOM-identity preservation across unrelated
    ##   parent re-runs is therefore not a guarantee inside parametric
    ##   subtrees in v2; the boundary that *is* preserved is the
    ##   `mountUiHot` mount point. Editing one mount's components leaves
    ##   the DOM under every other mount untouched.
    expectKind procDef, nnkProcDef
    let implSym = procDef.name
    let h = symBodyHash(implSym)
    let info = procDef.lineInfoObj()
    let locStr = info.filename & ":" & $info.line & ":" & $info.column
    let locLit = newLit(locStr)

    # `params[0]` is the return type slot; subsequent entries are
    # IdentDefs — one per group of parameters sharing a type.
    let isParametric = procDef.params.len > 1

    var dispatchProc: NimNode
    if isParametric:
      let (newParams, argNames) = cloneParamsWithFreshNames(procDef.params)
      let returnType = procDef.params[0].copyNimTree
      let body = buildParametricDispatch(realName, locLit, returnType, argNames)
      dispatchProc = newProc(name = realName, body = body)
      dispatchProc.params = newParams
    else:
      # Zero-arg path — preserved verbatim from v1 (per-slot memo via
      # `hmrInvokeComponent`).
      dispatchProc = newProc(
        name = realName,
        params = @[ident"Node"],
        body = newCall(bindSym"hmrInvokeComponent", locLit))

    # Module-top registration. The `let regVar = block: ...; true`
    # construct runs the block at module init time. Re-evaluating the
    # block on bundle reload (because the new bundle has its own JS
    # globals and re-runs init) hits hmrRegisterFactory which compares
    # hashes and writes the slot signal only when the body's effective
    # code actually changed.
    let regVar = genSym(nskLet, "isonimHmrReg_" & $realName)
    let factoryCast = quote do:
      hmrRegisterFactory(`locStr`, `h`, toJs(`implSym`))
      true
    let registration = newLetStmt(regVar, newBlockStmt(factoryCast))

    # Emit a `<ProcName>Loc*: string = "<full-location>"` const so user
    # code (especially tests) can refer to the slot without depending
    # on the absolute file path the macro embedded.
    let locConstName = ident($realName & "Loc")
    let locConst = newConstStmt(
      postfix(locConstName, "*"),
      newLit(locStr))

    result = newStmtList(procDef, dispatchProc, registration, locConst)

  macro uiComponent*(procDef: untyped): untyped =
    ## Stage 1 of the pragma. Renames the user's proc with a genSym'd
    ## "_impl" suffix so the original name can be reused for the
    ## dispatcher proc, and forwards to the typed analyzer.
    expectKind procDef, nnkProcDef
    let realName = procDef.name
    procDef.name = genSym(nskProc, $realName & "_impl")
    result = newCall(bindSym"uiComponentTyped", realName, procDef)

  macro bootstrapHmr*(): untyped =
    ## Place this at the bottom of every module that defines
    ## `{.uiComponent.}` procs. In v1 this is mostly a no-op (each
    ## component pragma already emits its own registration) but we
    ## keep the call so future versions (which may want to do a
    ## per-module sweep) can hook in without changing user code.
    result = newStmtList()

else:
  # `-d:isonimHmr` not set, or not the JS target. The pragma is a
  # transparent no-op: user's proc keeps its name, body, and behaviour;
  # callers reach it directly without going through any registry.
  macro uiComponent*(procDef: untyped): untyped =
    procDef

  macro bootstrapHmr*(): untyped =
    result = newStmtList()
